name: LearnGun
description: Professional Learnpress LMS app.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.2.0+25
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #BASE
  flutter_svg: ^1.0.3
  flutter_lints: ^2.0.1
  flutter_math_fork: ^0.6.1

  #STATE MANAGEMENT
  provider: ^6.0.2
  get: ^4.6.3

  #WEB
  flutter_html: ^3.0.0-alpha.2
  dio: ^4.0.6
  http: ^0.13.4
  webview_flutter: ^3.0.4
  flutter_inappwebview: ^5.4.3+7
  html_unescape: ^2.0.0
  url_launcher: ^6.0.20
  connectivity_plus: ^2.2.1

  #ICONS
  font_awesome_flutter: ^10.1.0
  cupertino_icons: ^1.0.4

  #payment
  flutter_stripe: ^3.0.0
  upi_india: ^3.0.1
  in_app_purchase: ^3.0.2
  google_mobile_ads: ^1.2.0
  razorpay_flutter: ^1.3.0

  #AUTHENTICATION
  google_sign_in: ^5.3.1
  flutter_facebook_auth: ^4.3.4
  the_apple_sign_in: ^1.1.1

  #MEDIA PlAYER
  youtube_player_flutter: ^8.1.0
  better_player:
    path: ./plugins/betterplayer-0.0.63
  zoom: ^1.0.3+5 #delete this if zoom sdk isn't needed
  just_audio: 
    path: ./plugins/just_audio
  flutter_ringtone_player: ^3.2.0

  #UTILS
  intl: ^0.17.0
  flutter_native_splash: ^2.1.3+1
  extended_image: ^6.0.2+1
  json_annotation: ^4.4.0
  flutter_screenutil: ^5.5.3+1
  google_fonts: ^3.0.0
  pretty_dio_logger: ^1.2.0-beta-1
  
  #TOOLS
  image_picker: ^0.8.4+11
  flutter_windowmanager: ^0.2.0
  share_plus: ^4.0.3
  screenshot: ^1.2.3
  permission_handler: ^8.3.0
  advance_pdf_viewer_fork: ^2.0.0
  uni_links: ^0.5.1

  #STORAGE
  path_provider: ^2.0.9
  shared_preferences: ^2.0.13
  flutter_downloader: ^1.7.4
  android_path_provider: ^0.3.0

  #FIREBASE
  firebase_core: ^1.19.2
  firebase_messaging: ^12.0.0
  firebase_in_app_messaging: ^0.6.0+19

  #UI
  badges: ^2.0.2
  percent_indicator: ^4.0.0
  material_floating_search_bar: ^0.3.7
  flutter_rating_bar: ^4.0.0
  carousel_slider: ^4.0.0
  persistent_bottom_nav_bar: ^4.0.2
  pull_to_refresh: ^2.0.0
  
dependency_overrides:
  image_picker_android: 0.8.4+13

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.5
  build_runner: ^2.1.8
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  assets:
    - assets/
    - assets/flags/
    - translations/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png